In [1]:
import seaborn as sns
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 
import scipy
import PIL
import requests

In [39]:
# load data, removing spaces in column headers
columns = ["Customer_ID", "Age", "Gender", "Item_Purchased", "Item_Category", "Purchase_Amount_(USD)", "Location", "Color", "Season", "Review_Rating", "Subscription_Status", "Shipping_Type", "Discount_Applied", "Promo_Code_Used", "Previous_Purchases", "Payment_Method", "Frequency_of_Purchases"]
df = pd.read_csv("../data/Customers3.csv", header = 0, names = columns)
# df

Identifying Shopper Loyalty by Sorting the Original Dataframe by Previous Purchase Volume and Purchase Amount ($)

In [ ]:
# sort original dataframe by volume of previous purchases and purchase amounts (highest first) to identify most loyal shoppers
df_sorted = df.sort_values(by=['Previous_Purchases', 'Purchase_Amount_(USD)'], ascending = False)
# df_sorted = df.sort_values(by=['Previous_Purchases', 'Purchase_Amount_(USD)', 'Frequency_of_Purchases'], ascending = False) # can add in frequency of purchases
df_sorted

,Customer_ID,Age,Gender,Item_Purchased,Item_Category,Purchase_Amount_(USD),Location,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Frequency_of_Purchases
455,456,54,Male,Blouse,Clothing,100,Utah,Gold,Fall,3.6,Yes,Store Pickup,Yes,Yes,50,Debit Card,Fortnightly
992,993,46,Male,Jacket,Outerwear,99,Louisiana,Gray,Winter,4.6,Yes,Express,Yes,Yes,50,Debit Card,Weekly
1737,1738,42,Male,Jewelry,Accessories,98,Ohio,Gray,Summer,4.2,No,Store Pickup,No,No,50,Venmo,Bi-Weekly
2229,2230,70,Male,Pants,Clothing,97,Minnesota,Silver,Fall,3.9,No,Express,No,No,50,Venmo,Monthly
2484,2485,60,Male,Hoodie,Clothing,97,New Hampshire,Green,Summer,4.8,No,2-Day Shipping,No,No,50,Cash,Every 3 Months
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,105,55,Male,Sunglasses,Accessories,24,New Hampshire,Pink,Spring,4.4,Yes,2-Day Shipping,Yes,Yes,1,PayPal,Monthly
3332,3333,27,Female,T-shirt,Clothing,23,Washington,Silver,Summer,3.1,No,2-Day Shipping,No,No,1,PayPal,Bi-Weekly
1663,1664,43,Male,Shirt,Clothing,22,Maine,Gold,Summer,3.5,No,Standard,Yes,Yes,1,Cash,Bi-Weekly
2149,2150,38,Male,Sandals,Footwear,21,Hawaii,Orange,Winter,4.0,No,Standard,No,No,1,Bank Transfer,Weekly
3142,3143,23,Female,Sneakers,Footwear,21,Kansas,Magenta,Winter,4.0,No,2-Day Shipping,No,No,1,Venmo,Quarterly

Create a Sample of 500 Random Values from the Original Dataframe

In [30]:
# create smaller sample of 500 random values from the original dataframe
np.random.seed(10)
rand_500 = df.sample(n=500) 
rand_500

,Customer_ID,Age,Gender,Item_Purchased,Item_Category,Purchase_Amount_(USD),Location,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment Method,Frequency of Purchases
193,194,36,Male,Belt,Accessories,100,North Dakota,Silver,Fall,3.0,Yes,Standard,Yes,Yes,29,Venmo,Annually
936,937,31,Male,Shoes,Footwear,84,Maine,Pink,Summer,2.7,Yes,Free Shipping,Yes,Yes,28,Cash,Weekly
2625,2626,30,Male,Skirt,Clothing,51,Colorado,Cyan,Summer,2.7,No,Standard,No,No,31,Credit Card,Weekly
234,235,20,Male,Gloves,Accessories,39,South Dakota,Silver,Summer,3.7,Yes,Next Day Air,Yes,Yes,24,Credit Card,Weekly
3823,3824,50,Female,Shirt,Clothing,42,California,Gold,Summer,3.0,No,Standard,No,No,27,Bank Transfer,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,1458,58,Male,Shirt,Clothing,57,Pennsylvania,Gray,Spring,4.7,No,Express,Yes,Yes,47,Venmo,Fortnightly
3232,3233,45,Female,T-shirt,Clothing,34,Massachusetts,White,Spring,4.0,No,Next Day Air,No,No,19,Bank Transfer,Monthly
1970,1971,28,Male,Belt,Accessories,94,Maryland,Indigo,Spring,2.9,No,Next Day Air,No,No,4,Credit Card,Bi-Weekly
3538,3539,56,Female,Shoes,Footwear,63,Iowa,White,Spring,4.5,No,Store Pickup,No,No,21,Venmo,Monthly
349,350,37,Male,Hat,Accessories,87,Arizona,Green,Winter,3.7,Yes,2-Day Shipping,Yes,Yes,3,Bank Transfer,Bi-Weekly

Creating a Sample of the Top 500 Values based on Previous Purchases and Purchase Amounts

In [35]:
# create smaller sample of 500 top values from the sorted dataframe
top_500 = df_sorted[:500]
top_500

,Customer_ID,Age,Gender,Item_Purchased,Item_Category,Purchase_Amount_(USD),Location,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment Method,Frequency of Purchases
455,456,54,Male,Blouse,Clothing,100,Utah,Gold,Fall,3.6,Yes,Store Pickup,Yes,Yes,50,Debit Card,Fortnightly
992,993,46,Male,Jacket,Outerwear,99,Louisiana,Gray,Winter,4.6,Yes,Express,Yes,Yes,50,Debit Card,Weekly
1737,1738,42,Male,Jewelry,Accessories,98,Ohio,Gray,Summer,4.2,No,Store Pickup,No,No,50,Venmo,Bi-Weekly
2229,2230,70,Male,Pants,Clothing,97,Minnesota,Silver,Fall,3.9,No,Express,No,No,50,Venmo,Monthly
2484,2485,60,Male,Hoodie,Clothing,97,New Hampshire,Green,Summer,4.8,No,2-Day Shipping,No,No,50,Cash,Every 3 Months
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,1005,33,Male,Backpack,Accessories,79,Tennessee,Black,Summer,4.8,Yes,2-Day Shipping,Yes,Yes,44,Cash,Annually
2254,2255,24,Male,Belt,Accessories,79,North Dakota,Gold,Winter,4.2,No,Store Pickup,No,No,44,PayPal,Every 3 Months
3894,3895,66,Female,Skirt,Clothing,78,Connecticut,White,Spring,3.9,No,2-Day Shipping,No,No,44,Credit Card,Every 3 Months
888,889,49,Male,Scarf,Accessories,77,New Hampshire,Gold,Spring,3.6,Yes,Express,Yes,Yes,44,Cash,Annually
3158,3159,30,Female,Jewelry,Accessories,77,Mississippi,Gray,Winter,4.9,No,2-Day Shipping,No,No,44,Credit Card,Monthly

These 2 samples of 500 values will allow us to cross-reference our financially-significant shoppers sample against a random sample of shoppers