In [1]:
import seaborn as sns
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 
import scipy
import PIL
import requests

In [3]:
# load data, removing spaces in column headers
columns = ["Customer_ID", "Age", "Gender", "Item_Purchased", "Item_Category", "Purchase_Amount_(USD)", "Location", "Color", "Season", "Review_Rating", "Subscription_Status", "Shipping_Type", "Discount_Applied", "Promo_Code_Used", "Previous_Purchases", "Payment Method", "Frequency of Purchases"]
df = pd.read_csv("../data/Customers3.csv", header = 0, names = columns)
df

,Customer_ID,Age,Gender,Item_Purchased,Item_Category,Purchase_Amount_(USD),Location,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [ ]:
# sort original dataframe by volume of previous purchases and purchase amounts (highest first) to identify most loyal shoppers
df_sorted = df.sort_values(by=['Previous_Purchases', 'Purchase_Amount_(USD)'], ascending = False)
df_sorted

,Customer_ID,Age,Gender,Item_Purchased,Item_Category,Purchase_Amount_(USD),Location,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment Method,Frequency of Purchases
455,456,54,Male,Blouse,Clothing,100,Utah,Gold,Fall,3.6,Yes,Store Pickup,Yes,Yes,50,Debit Card,Fortnightly
992,993,46,Male,Jacket,Outerwear,99,Louisiana,Gray,Winter,4.6,Yes,Express,Yes,Yes,50,Debit Card,Weekly
1737,1738,42,Male,Jewelry,Accessories,98,Ohio,Gray,Summer,4.2,No,Store Pickup,No,No,50,Venmo,Bi-Weekly
2229,2230,70,Male,Pants,Clothing,97,Minnesota,Silver,Fall,3.9,No,Express,No,No,50,Venmo,Monthly
2484,2485,60,Male,Hoodie,Clothing,97,New Hampshire,Green,Summer,4.8,No,2-Day Shipping,No,No,50,Cash,Every 3 Months
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,105,55,Male,Sunglasses,Accessories,24,New Hampshire,Pink,Spring,4.4,Yes,2-Day Shipping,Yes,Yes,1,PayPal,Monthly
3332,3333,27,Female,T-shirt,Clothing,23,Washington,Silver,Summer,3.1,No,2-Day Shipping,No,No,1,PayPal,Bi-Weekly
1663,1664,43,Male,Shirt,Clothing,22,Maine,Gold,Summer,3.5,No,Standard,Yes,Yes,1,Cash,Bi-Weekly
2149,2150,38,Male,Sandals,Footwear,21,Hawaii,Orange,Winter,4.0,No,Standard,No,No,1,Bank Transfer,Weekly
3142,3143,23,Female,Sneakers,Footwear,21,Kansas,Magenta,Winter,4.0,No,2-Day Shipping,No,No,1,Venmo,Quarterly

In [26]:
# create smaller sample of 500
np.random.seed(10)
df_500 = df_sorted.sample(n=500) # not grabbing top 500 it seems
df_500

,Customer_ID,Age,Gender,Item_Purchased,Item_Category,Purchase_Amount_(USD),Location,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment Method,Frequency of Purchases
1249,1250,62,Male,Boots,Footwear,50,Oregon,Peach,Winter,4.5,No,Express,Yes,Yes,48,Venmo,Fortnightly
779,780,60,Male,Dress,Clothing,94,Utah,Blue,Spring,4.6,Yes,Express,Yes,Yes,38,Cash,Annually
1546,1547,60,Male,Sneakers,Footwear,51,Oregon,Purple,Summer,3.8,No,Express,Yes,Yes,17,Bank Transfer,Annually
2766,2767,66,Female,Dress,Clothing,91,Tennessee,Cyan,Winter,2.8,No,Standard,No,No,47,Credit Card,Monthly
566,567,55,Male,Sneakers,Footwear,93,Alabama,Indigo,Spring,3.6,Yes,Store Pickup,Yes,Yes,1,Debit Card,Fortnightly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3118,3119,61,Female,Shorts,Clothing,97,Virginia,Blue,Summer,4.7,No,Standard,No,No,31,Debit Card,Quarterly
3115,3116,26,Female,Scarf,Accessories,53,South Dakota,Charcoal,Fall,4.1,No,Free Shipping,No,No,9,Bank Transfer,Bi-Weekly
133,134,52,Male,Sweater,Clothing,65,Montana,Violet,Winter,2.5,Yes,Next Day Air,Yes,Yes,25,Venmo,Annually
699,700,50,Male,Handbag,Accessories,46,Connecticut,Charcoal,Fall,2.6,Yes,2-Day Shipping,Yes,Yes,5,PayPal,Weekly
2347,2348,37,Male,Belt,Accessories,64,California,Gray,Fall,4.2,No,Express,No,No,46,Cash,Every 3 Months